### ISSUE TITLE
Availability of code used for evaluating on Quixbugs, hardware requirements

### ISSUE THREAD

**Issue by DoHuber** [FSE2021anonymous/Recoder#4]
Dear Authors,

I am researching attention mechanisms in Automatic Program Repair approaches, and Recoder is a strong candidate for inclusion due to its novel architecture and high performance. The primary dataset I'm considering is Quixbugs. Since Recoder offers high performance on that dataset, would it be possible for you to also share the code used to evaluate Recoder on Quixbugs? 

Furthermore, I would like to ask what hardware resources were used in the training of Recoder.

Thanks in Advance and Best Regards

**Comment by pkuzqh** [comment]
Thanks for the attention. I need some time to reorganize our test code on Quixbugs. Please wait for a while.

**Comment by DoHuber** [comment]
Thank you for your quick reply. I noticed that you uploaded files and instructions relating to Quixbugs over the previous weeks, but I'm afraid that I have not been able to get them to run correctly. There seems to be a file named `runqfix.py` missing. Is this still work-in-progress or am I missing something?

In the meantime, would it be possible for you to share which bugs out of the Quixbugs dataset were successfully fixed by Recoder?
