### ISSUE TITLE
How to acquire Recoder's training dataset?

### ISSUE THREAD

**Issue by Abdulaziz-Alhefdhi** [FSE2021anonymous/Recoder#6]
Dear Authors,
Thank you very much for the great work published in this Github repository. According to my understanding of the paper, there are 103,585 data points used for training Recoder. How can we acquire and investigate these training instances? I failed in retrieving them from Docker, and the provided link to the raw data is on a Pickle format, which is not human-readable. It is much appreciated if you can provide us with an easier way to reach the training dataset.

**Comment by pkuzqh** [comment]
You can use the pickle library to load the training dataset. And then you will get a dict with raw java code.
