### ISSUE TITLE
Loading Data issue

### ISSUE THREAD

**Issue by sharod** [FSE2021anonymous/Recoder#8]
I am trying to train the model without the docker. I have downloaded the data0.pkl and data1.pkl. They are mentioned as raw data. Do they need pre-processing? The paths in the Dataset.py code are hardcoded and the filenames do not match data0.pkl and data1.pkl. I have changed them accordingly. But do they need the call to the preprocess function? As passing them to the preprocess function is throwing error. I have thus loaded the data directly into the self.data variable. But now the dataloader is empty and thus training is not happening at all. Please help soon with this data issue.

**Comment by pkuzqh** [comment]
Actually, you can copy the processed data from the docker to run. Also, you can use the following code to process data, https://disk.pku.edu.cn:443/link/1CE67CD4F22ABDAF462F76A8903E8758.

**Comment by sharod** [comment]
Thank you for the prompt reply with the data.
