### ISSUE TITLE
AST format

### ISSUE THREAD

**Issue by sharod** [FSE2021anonymous/Recoder#9]
Hi,
The data provided has the AST in the form of a string sequence. I am preparing a new dataset. I have the AST. Can you please share how did you convert the AST to the string sequence? Please help as soon as possible.

**Comment by pkuzqh** [comment]
You can use the runreplacesolveYES2.py to generate the AST string sequence.

**Comment by jz48** [comment]
I didn't find the script runreplacesolveYES2.py in the repo?
